matlab -nodisplay -nodesktop -r "sim_true_tree(1, 1); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(2, 2); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(3, 3); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(4, 4); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(5, 5); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(6, 6); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(7, 7); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(8, 8); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(9, 9); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(10, 10); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(11, 11); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(12, 12); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(13, 13); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(14, 14); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(15, 15); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(16, 16); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(17, 17); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(18, 18); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(19, 19); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(20, 20); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(21, 21); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(22, 22); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(23, 23); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(24, 24); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(25, 25); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(26, 26); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(27, 27); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(28, 28); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(29, 29); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(30, 30); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(31, 31); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(32, 32); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(33, 33); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(34, 34); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(35, 35); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(36, 36); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(37, 37); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(38, 38); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(39, 39); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(40, 40); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(41, 41); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(42, 42); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(43, 43); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(44, 44); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(45, 45); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(46, 46); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(47, 47); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(48, 48); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(49, 49); quit;" &
matlab -nodisplay -nodesktop -r "sim_true_tree(50, 50); quit;" &
