---
title: "PBC Analysis"
author: "Richard Payne"
date: '2023-05-20'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Brier scores from PBC dataset:

```{r}
library(targets)
library(ggplot2)
library(tidyr)
library(dplyr)
library(randomForestSRC)
library(BART)
tar_load(c(brier_bart, brier_forest, brier_tree, brier_cox, brier_miss_cox))
brier_cox2 <- data.frame(
    type = rep(c("brier", "brier_miss"), each = nrow(brier_cox) * ncol(brier_cox)),
    brier = c(
      c(as.matrix(brier_cox)),
      c(as.matrix(brier_miss_cox))
    ),
    time = rep(c(617, 1181, 1788, 2691, 3608), each = 5),
    model = "cox"
  )
brier <- bind_rows(brier_bart, brier_forest) %>%
  pivot_longer(
    c("brier", "brier_miss"),
    names_to = "type",
    values_to = "brier"
  )
brier_tree <- brier_tree %>%
  pivot_longer(everything(), names_to = "t_chr", values_to = "brier_miss") %>%
  mutate(
    time = case_when(
      t_chr == "V1" ~ 617,
      t_chr == "V2" ~ 1181,
      t_chr == "V3" ~ 1788,
      t_chr == "V4" ~ 2691,
      t_chr == "V5" ~ 3608
    ),
    model = "tree"
  ) %>%
  select(-t_chr) %>%
  pivot_longer("brier_miss", names_to = "type", values_to = "brier")
brier <- bind_rows(brier, brier_tree, brier_cox2) %>%
  mutate(
    Method = case_when(
      model == "cox" ~ "Cox",
      model == "forest" ~ "Forest",
      model == "tree" ~ "THM",
      TRUE ~ model
    ),
    Method = factor(Method, c("Cox", "BART", "Forest", "THM")),
    percentile = case_when(
      time == 617 ~ "10%",
      time == 1181 ~ "25%",
      time == 1788 ~ "50%",
      time == 2691 ~ "75%",
      time == 3608 ~ "90%"
    ),
    percentile = factor(percentile, c("10%", "25%", "50%", "75%", "90%"))
  )
ggplot(
  filter(brier, type == "brier_miss"),
  aes(percentile, brier, fill = Method)) +
  scale_fill_grey(start = 0.35, end = 0.95) +
  geom_boxplot() +
  labs(x = "Survival Percentile", y = "Brier Score") +
  theme_bw()

ggplot(
  filter(brier, type == "brier_miss"),
  aes(percentile, brier, fill = Method, group = Method, shape = Method)) +
  geom_point(position = position_dodge(width = 0.6), size = 3) +
  scale_color_grey() +
  theme_bw() +
  scale_shape(solid = FALSE) +
  labs(x = "Survival Percentile", y = "Brier Score")

brier_mean <- brier %>%
  filter(type == "brier_miss") %>%
  group_by(percentile, Method) %>%
  summarize(
    se = sd(brier) / sqrt(n()),
    brier = mean(brier),
    .groups = "drop"
  ) %>%
  mutate(lb = brier - 2 * se, ub = brier + 2 * se)

p <- ggplot(
  brier_mean,
  aes(percentile, brier, fill = Method, group = Method, shape = Method)) +
  geom_point(position = position_dodge(width = .6), size = 3) +
  geom_errorbar(
    aes(ymin = lb, ymax = ub),
    position = position_dodge(width = 0.6),
    width = 0.5
  ) +
  scale_color_grey() +
  theme_bw() +
  scale_shape_manual(values = c(0:2, 4)) +
  labs(x = "Survival Percentile", y = "Brier Score")

ggsave("pbc_brier.jpg", plot = p, width = 7, height = 3)
```
